name: rixin

on:
  push:
    branches: [master]
  
jobs:
  rixin:
    runs-on: ubuntu-latest

    steps:
    - name: checkout codes
      uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '14.15.1'

    - name: cache node_modules # 设置包缓存目录，避免每次下载
      uses: actions/cache@v1
      with:
        path: ～/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: install dependencies
      run: npm install

    - name: build vuepress
      run: npm run build

    - name: deploy to github pages
      uses: crazy-max/ghaction-github-pages@v2
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
        target_branch: pages
        build_dir: docs/.vuepress/dist 
      
    - name: deploy to github other repository
      env:
        GITHUB_REPO: github.com/fengrixin/fengrixin.github.io
      run: |
        cd docs/.vuepress/dist
        git config user.name "fengrixin"
        git config user.email "fengrixin@yeah.net"
        git push --force --quiet "https://${{ secrets.ACCESS_RIXIN_TOKEN }}@$GITHUB_REPO" master:master