name: rixin

on:
  push:
    branches: [master]
  
jobs:
  rixin:
    runs-on: ubuntu-latest

    steps:
    - name: checkout codes
      uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '14.15.1'

    - name: cache node_modules # 设置包缓存目录，避免每次下载
      uses: actions/cache@v2
      id: npm-cache
      with:
        path: ｜
          **/node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: install dependencies
      if: steps.npm-cache.outputs.cache-hit != 'true'
      run: npm install

    - name: build vuepress
      run: npm run build

    - name: deploy to github pages
      use: crazy-max/ghaction-github-pages@v2
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
        target_branch: gh-pages
        build_dir: docs/.vuepress/dist